---
action:
    parameters:
        committer: '{{ trigger.committer }}'
        repository_url: '{{ trigger.repository_url }}'
        commit_message: '{{ trigger.commit_message }}'
        branch: '{{ trigger.branch }}'
    ref: ripeops.update_pack
criteria: {}
enabled: true
name: update_pack
pack: ripeops
ref: git.update_pack
tags: []
trigger:
    parameters: {}
    ref: git.head_sha_monitor
    type: git.head_sha_monitor
type:
    parameters: {}
    ref: standard
uid: rule:git:update_pack
